name: report
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"

      - name: Download certificates
        run: go run cmd/shaken/*.go download --html --includeCa --outDir x_certs shaken-urls.txt

      - name: Run lint
        run: go run cmd/shaken/*.go lint --html x_certs

      - name: Publish report
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: x_report
          CLEAN: true
